spring.application.name=backend

# 1. Cấu hình Cổng chạy Backend (Mặc định là 8080)
server.port=8080

# 2. Cấu hình kết nối PostgreSQL Database
# (Thay 'bossfarm_db' bằng tên Database của bạn trong PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/BossFarmDB

# Tài khoản mặc định của PostgreSQL
spring.datasource.username=postgres

# MẬT KHẨU: Thay '123456' bằng mật khẩu thật của tài khoản postgres trên máy bạn
spring.datasource.password=Lebatiem1

# Driver kết nối PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# 3. Cấu hình JPA / Hibernate
# ddl-auto=update: Tự động tạo/cập nhật bảng DB theo code Java mà không làm mất dữ liệu
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
